# https://open-telemetry.github.io/opentelemetry-helm-charts

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.168.0
    chart: opentelemetry-collector
    helm:
      releaseName: otel-collector
      valuesObject:
        mode: deployment
        fullnameOverride: otel-collector
        replicaCount: 2
        image:
          repository: otel/opentelemetry-collector-contrib
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
        ports:
          jaeger-compact:
            enabled: false
          jaeger-thrift:
            enabled: false
          jaeger-grpc:
            enabled: false
          zipkin:
            enabled: false
        config:
          receivers:
            jaeger: null
            zipkin: null
          exporters:
            otlphttp/loki:
              endpoint: http://loki.monitoring.svc.cluster.local:3100/otlp
          service:
            pipelines:
              logs:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlphttp/loki]
              traces:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [debug]
              metrics:
                receivers: [otlp, prometheus]
                processors: [memory_limiter, batch]
                exporters: [debug]
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
